# Generated by Django 4.0 on 2021-12-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='restaurantmanager',
            options={},
        ),
        migrations.AlterModelOptions(
            name='siteadmin',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('مدیر سایت', 'مدیر سایت'), ('مدیر رستوران', 'مدیر رستوران'), ('مشتری', 'مشتری')], max_length=20),
        ),
    ]
