# Generated by Django 4.0 on 2022-01-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraddress_address_remove_useraddress_user_and_more'),
        ('online_food_ordering', '0005_remove_order_user_address_order_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
