# Generated by Django 4.0 on 2022-01-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='primary',
            field=models.BooleanField(),
        ),
    ]
