# Generated by Django 3.2.11 on 2022-01-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_customer_alter_address_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
