# Generated by Django 4.0 on 2021-12-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_food_ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'branches'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
