# Generated by Django 4.0 on 2022-01-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_food_ordering', '0002_alter_category_name_alter_food_name_alter_meal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'سفارش'), (1, 'ثبت'), (2, 'ارسال'), (3, 'تحویل')]),
        ),
    ]
