# Generated by Django 4.0 on 2021-12-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_food_ordering', '0003_remove_food_meal_food_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('سفارش', 'سفارش'), ('ثبت', 'ثبت'), ('ارسال', 'ارسال'), ('تحویل', 'تحویل')], max_length=10),
        ),
    ]
