# Generated by Django 4.0 on 2021-12-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_food_ordering', '0005_remove_orderitem_menu_item_orderitem_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='online_food_ordering.menuitem'),
        ),
    ]
