# Generated by Django 4.0 on 2022-01-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_food_ordering', '0005_remove_order_user_address_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
