# Generated by Django 3.2.11 on 2022-01-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_food_ordering', '0008_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
