# Generated by Django 3.2.11 on 2022-01-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_food_ordering', '0009_alter_branch_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
